import Accelerate
import XCTest
@testable import FireRedVADKit

/// Parity tests comparing Swift implementation against Python kaldi_native_fbank + PyTorch reference.
///
/// Reference data generated by: FireRedVAD/test_reference.py
/// Binary format: 4-byte ndim, then 4-byte per dimension, then raw float32 data.
final class ParityTests: XCTestCase {
    /// Path to reference data generated by Python
    static let testDataDir = "/Volumes/DATA/ane-research/FireRedVAD/test_data"

    // MARK: - Helpers

    /// Load a .bin file written by test_reference.py (header: ndim + shape + raw float32)
    static func loadBin(_ name: String) throws -> (data: [Float], shape: [Int]) {
        let url = URL(fileURLWithPath: "\(testDataDir)/\(name)")
        let raw = try Data(contentsOf: url)

        var offset = 0
        func readUInt32() -> UInt32 {
            let val = raw.withUnsafeBytes { ptr in
                ptr.load(fromByteOffset: offset, as: UInt32.self)
            }
            offset += 4
            return val
        }

        let ndim = Int(readUInt32())
        var shape = [Int]()
        for _ in 0 ..< ndim {
            shape.append(Int(readUInt32()))
        }

        let count = shape.reduce(1, *)
        var data = [Float](repeating: 0, count: count)
        raw.withUnsafeBytes { ptr in
            guard let baseAddr = ptr.baseAddress else { return }
            let src = baseAddr.advanced(by: offset).assumingMemoryBound(to: Float.self)
            for i in 0 ..< count {
                data[i] = src[i]
            }
        }

        return (data: data, shape: shape)
    }

    /// Compute max absolute difference between two arrays.
    static func maxAbsDiff(_ a: [Float], _ b: [Float]) -> Float {
        precondition(a.count == b.count, "Array size mismatch: \(a.count) vs \(b.count)")
        var maxDiff: Float = 0
        for i in 0 ..< a.count {
            maxDiff = max(maxDiff, abs(a[i] - b[i]))
        }
        return maxDiff
    }

    /// Compute mean absolute difference.
    static func meanAbsDiff(_ a: [Float], _ b: [Float]) -> Float {
        precondition(a.count == b.count)
        var sum: Float = 0
        for i in 0 ..< a.count {
            sum += abs(a[i] - b[i])
        }
        return sum / Float(a.count)
    }

    // MARK: - Fbank Parity

    func testFbankParity() throws {
        // Load reference: audio in int16 scale, fbank output
        let (audioInt16, audioShape) = try Self.loadBin("audio_int16_as_float.bin")
        let (refFbank, fbankShape) = try Self.loadBin("fbank.bin")

        XCTAssertEqual(audioShape, [1_600], "Audio should be 1600 samples")
        XCTAssertEqual(fbankShape, [8, 80], "Fbank should be 8 frames × 80 dims")

        // Run Swift fbank
        let fbank = KaldiFbank()
        let (swiftFbank, numFrames) = fbank.compute(audio: audioInt16)

        XCTAssertEqual(numFrames, 8, "Expected 8 frames from 1600 samples")
        XCTAssertEqual(swiftFbank.count, 8 * 80)

        let maxDiff = Self.maxAbsDiff(swiftFbank, refFbank)
        let meanDiff = Self.meanAbsDiff(swiftFbank, refFbank)

        print("FBANK PARITY:")
        print("  Max abs diff:  \(maxDiff)")
        print("  Mean abs diff: \(meanDiff)")
        print("  Swift range:   [\(swiftFbank.min() ?? .nan), \(swiftFbank.max() ?? .nan)]")
        print("  Ref range:     [\(refFbank.min() ?? .nan), \(refFbank.max() ?? .nan)]")

        // Print first frame comparison
        print("  First 5 bins (Swift): \(Array(swiftFbank[0 ..< 5]))")
        print("  First 5 bins (Ref):   \(Array(refFbank[0 ..< 5]))")

        // Tolerance: fbank differences < 0.1 (log scale, ~0.5% relative)
        XCTAssertLessThan(maxDiff, 0.1, "Fbank max diff too large: \(maxDiff)")
    }

    // MARK: - CMVN Parity

    func testCMVNParity() throws {
        // Load reference fbank and CMVN output
        let (refFbank, _) = try Self.loadBin("fbank.bin")
        let (refCmvn, cmvnShape) = try Self.loadBin("cmvn.bin")
        let (refMeans, _) = try Self.loadBin("cmvn_means.bin")
        let (refInvStd, _) = try Self.loadBin("cmvn_invstd.bin")

        XCTAssertEqual(cmvnShape, [8, 80])

        // Verify our hardcoded stats match Python's
        let meansDiff = Self.maxAbsDiff(CMVN.means, refMeans)
        let invStdDiff = Self.maxAbsDiff(CMVN.invStd, refInvStd)
        print("CMVN STATS:")
        print("  Means max diff:  \(meansDiff)")
        print("  InvStd max diff: \(invStdDiff)")
        XCTAssertLessThan(meansDiff, 1e-4, "CMVN means mismatch")
        XCTAssertLessThan(invStdDiff, 1e-4, "CMVN invStd mismatch")

        // Apply CMVN to reference fbank (to test CMVN in isolation)
        var cmvnInput = refFbank
        CMVN.apply(features: &cmvnInput, numFrames: 8)

        let maxDiff = Self.maxAbsDiff(cmvnInput, refCmvn)
        print("CMVN PARITY (on ref fbank):")
        print("  Max abs diff: \(maxDiff)")
        XCTAssertLessThan(maxDiff, 1e-4, "CMVN max diff too large")
    }

    // MARK: - End-to-end Fbank + CMVN

    func testFbankCMVNParity() throws {
        let (audioInt16, _) = try Self.loadBin("audio_int16_as_float.bin")
        let (refCmvn, _) = try Self.loadBin("cmvn.bin")

        let fbank = KaldiFbank()
        var (features, numFrames) = fbank.compute(audio: audioInt16)
        XCTAssertEqual(numFrames, 8)

        CMVN.apply(features: &features, numFrames: numFrames)

        let maxDiff = Self.maxAbsDiff(features, refCmvn)
        let meanDiff = Self.meanAbsDiff(features, refCmvn)
        print("FBANK+CMVN PARITY:")
        print("  Max abs diff:  \(maxDiff)")
        print("  Mean abs diff: \(meanDiff)")

        XCTAssertLessThan(maxDiff, 0.1, "Fbank+CMVN pipeline max diff too large")
    }

    // MARK: - CoreML Inference Parity

    func testInferenceParity() throws {
        let (refCmvn, _) = try Self.loadBin("cmvn.bin")
        let (refProbs, probsShape) = try Self.loadBin("probs.bin")

        XCTAssertEqual(probsShape, [8], "Expected 8 probs")

        // Runtime compile from .mlmodel source
        let sourceURL = URL(fileURLWithPath: "/Volumes/DATA/ane-research/FireRedVAD/FireRedVAD_Stream_N8_nn.mlmodel")
        let inference = try FireRedVADInference(modelSourceURL: sourceURL, computeUnits: .all)

        let swiftProbs = try inference.predict(features: refCmvn, numFrames: 8)

        let maxDiff = Self.maxAbsDiff(swiftProbs, refProbs)
        print("INFERENCE PARITY (on ref CMVN features):")
        print("  Swift probs: \(swiftProbs)")
        print("  Ref probs:   \(refProbs)")
        print("  Max abs diff: \(maxDiff)")

        // neuralNetwork Float32: expect near-exact match
        XCTAssertLessThan(maxDiff, 0.001, "Inference max diff too large")
    }

    // MARK: - Full Pipeline Parity

    func testFullPipelineParity() throws {
        let (audioInt16, _) = try Self.loadBin("audio_int16_as_float.bin")
        let (refProbs, _) = try Self.loadBin("probs.bin")

        let fbank = KaldiFbank()
        var (features, numFrames) = fbank.compute(audio: audioInt16)
        XCTAssertEqual(numFrames, 8)

        CMVN.apply(features: &features, numFrames: numFrames)

        let sourceURL = URL(fileURLWithPath: "/Volumes/DATA/ane-research/FireRedVAD/FireRedVAD_Stream_N8_nn.mlmodel")
        let inference = try FireRedVADInference(modelSourceURL: sourceURL, computeUnits: .all)
        let swiftProbs = try inference.predict(features: features, numFrames: 8)

        let maxDiff = Self.maxAbsDiff(swiftProbs, refProbs)
        print("FULL PIPELINE PARITY:")
        print("  Swift probs: \(swiftProbs)")
        print("  Ref probs:   \(refProbs)")
        print("  Max abs diff: \(maxDiff)")

        // Full pipeline: fbank diff accumulates through CMVN + model
        XCTAssertLessThan(maxDiff, 0.01, "Full pipeline max diff too large")
    }
}

// MARK: - StreamVADPostprocessor Tests

final class PostprocessorTests: XCTestCase {
    func testSpeechDetection() {
        let pp = StreamVADPostprocessor()

        // 20 frames of high speech prob → should trigger speech
        let highProbs = [Float](repeating: 0.9, count: 20)
        let segs1 = pp.process(probs: highProbs)
        // No segment emitted yet (speech ongoing)
        XCTAssertTrue(segs1.isEmpty)
        XCTAssertTrue(pp.isSpeech)
        XCTAssertEqual(pp.state, .speech)
    }

    func testSpeechThenSilenceEmitsSegment() {
        let config = StreamVADPostprocessor.Config()
        let pp = StreamVADPostprocessor(config: config)

        // Start with silence, then speech
        let silence = [Float](repeating: 0.0, count: 5)
        _ = pp.process(probs: silence)
        XCTAssertEqual(pp.state, .silence)

        // Speech frames (enough to pass minSpeechFrame=8)
        let speech = [Float](repeating: 0.9, count: 30)
        _ = pp.process(probs: speech)
        XCTAssertTrue(pp.isSpeech)

        // Silence frames (enough to pass minSilenceFrame=20)
        let longSilence = [Float](repeating: 0.0, count: 30)
        let segs = pp.process(probs: longSilence)
        XCTAssertFalse(segs.isEmpty, "Should emit segment after speech→silence")
        XCTAssertEqual(pp.state, .silence)

        let seg = segs[0]
        XCTAssertGreaterThan(seg.endFrame, seg.startFrame)
        print("Segment: \(seg.startTimeMs)ms - \(seg.endTimeMs)ms")
    }

    func testPossibleSpeechTooShort() {
        let pp = StreamVADPostprocessor()

        // Only 3 speech frames (below minSpeechFrame=8) then silence
        let shortSpeech = [Float](repeating: 0.9, count: 3)
        _ = pp.process(probs: shortSpeech)

        let silence = [Float](repeating: 0.0, count: 5)
        let segs = pp.process(probs: silence)
        XCTAssertTrue(segs.isEmpty, "Too-short speech should not emit segment")
        XCTAssertEqual(pp.state, .silence)
    }

    func testReset() {
        let pp = StreamVADPostprocessor()

        let speech = [Float](repeating: 0.9, count: 20)
        _ = pp.process(probs: speech)
        XCTAssertTrue(pp.isSpeech)

        pp.reset()
        XCTAssertEqual(pp.state, .silence)
        XCTAssertFalse(pp.isSpeech)
    }

    func testWithRealModelOutput() throws {
        // Use actual model probs from the reference test data
        let (refCmvn, _) = try ParityTests.loadBin("cmvn.bin")

        let sourceURL = URL(fileURLWithPath: "/Volumes/DATA/ane-research/FireRedVAD/FireRedVAD_Stream_N8_nn.mlmodel")
        let inference = try FireRedVADInference(modelSourceURL: sourceURL, computeUnits: .all)
        let probs = try inference.predict(features: refCmvn, numFrames: 8)

        // All probs should be high (>0.8) for this speech segment
        for (i, p) in probs.enumerated() {
            XCTAssertGreaterThan(p, 0.8, "Frame \(i) prob \(p) should indicate speech")
        }

        // Feed to postprocessor
        let pp = StreamVADPostprocessor()
        let segs = pp.process(probs: probs)
        // Speech started but not ended — no segments yet
        XCTAssertTrue(segs.isEmpty)
        XCTAssertTrue(pp.isSpeech, "High probs should trigger speech state")
        print("Postprocessor state after real model output: \(pp.state)")
    }
}
